name = "MyWebsite"
uuid = "94ef4862-bd54-4bcc-8c02-a02f4109ca21"
version = "0.1.0"
authors = ["will "]

[deps]
Bonito = "824d6782-a2ef-11e9-3a09-e5662e0c26f8"
BonitoSites = "8b3cd1a5-63d9-421b-9fde-46b64b830918"
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[compat]
Bonito = "4.1.11"
BonitoSites = "0.1.0"
DocumenterTools = "0.1.21"
Markdown = "1.11.0"
Revise = "3.12.1"
